with-expecter: true
issue-845-fix: true
packages:
  github.com/johnknl/alog/internal/storage:
    interfaces:
      File:
      FileSystem:
    config:
      dir: internal/storage/mocks
      outpkg: mocks
