// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	storage "github.com/johnknl/alog/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockFileSystem is an autogenerated mock type for the FileSystem type
type MockFileSystem struct {
	mock.Mock
}

type MockFileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileSystem) EXPECT() *MockFileSystem_Expecter {
	return &MockFileSystem_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: name
func (_m *MockFileSystem) Create(name string) (storage.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 storage.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (storage.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) storage.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileSystem_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *MockFileSystem_Expecter) Create(name interface{}) *MockFileSystem_Create_Call {
	return &MockFileSystem_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *MockFileSystem_Create_Call) Run(run func(name string)) *MockFileSystem_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_Create_Call) Return(_a0 storage.File, _a1 error) *MockFileSystem_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_Create_Call) RunAndReturn(run func(string) (storage.File, error)) *MockFileSystem_Create_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function with given fields: _a0, _a1
func (_m *MockFileSystem) MkdirAll(_a0 string, _a1 fs.FileMode) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileSystem_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - _a0 string
//   - _a1 fs.FileMode
func (_e *MockFileSystem_Expecter) MkdirAll(_a0 interface{}, _a1 interface{}) *MockFileSystem_MkdirAll_Call {
	return &MockFileSystem_MkdirAll_Call{Call: _e.mock.On("MkdirAll", _a0, _a1)}
}

func (_c *MockFileSystem_MkdirAll_Call) Run(run func(_a0 string, _a1 fs.FileMode)) *MockFileSystem_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.FileMode))
	})
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) Return(_a0 error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_MkdirAll_Call) RunAndReturn(run func(string, fs.FileMode) error) *MockFileSystem_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: name
func (_m *MockFileSystem) Open(name string) (storage.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 storage.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (storage.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) storage.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockFileSystem_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockFileSystem_Expecter) Open(name interface{}) *MockFileSystem_Open_Call {
	return &MockFileSystem_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockFileSystem_Open_Call) Run(run func(name string)) *MockFileSystem_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_Open_Call) Return(_a0 storage.File, _a1 error) *MockFileSystem_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_Open_Call) RunAndReturn(run func(string) (storage.File, error)) *MockFileSystem_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: _a0
func (_m *MockFileSystem) ReadDir(_a0 string) ([]fs.DirEntry, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileSystem_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - _a0 string
func (_e *MockFileSystem_Expecter) ReadDir(_a0 interface{}) *MockFileSystem_ReadDir_Call {
	return &MockFileSystem_ReadDir_Call{Call: _e.mock.On("ReadDir", _a0)}
}

func (_c *MockFileSystem_ReadDir_Call) Run(run func(_a0 string)) *MockFileSystem_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) Return(_a0 []fs.DirEntry, _a1 error) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_ReadDir_Call) RunAndReturn(run func(string) ([]fs.DirEntry, error)) *MockFileSystem_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: _a0
func (_m *MockFileSystem) Remove(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFileSystem_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - _a0 string
func (_e *MockFileSystem_Expecter) Remove(_a0 interface{}) *MockFileSystem_Remove_Call {
	return &MockFileSystem_Remove_Call{Call: _e.mock.On("Remove", _a0)}
}

func (_c *MockFileSystem_Remove_Call) Run(run func(_a0 string)) *MockFileSystem_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_Remove_Call) Return(_a0 error) *MockFileSystem_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_Remove_Call) RunAndReturn(run func(string) error) *MockFileSystem_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: _a0
func (_m *MockFileSystem) Stat(_a0 string) (fs.FileInfo, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileSystem_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFileSystem_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - _a0 string
func (_e *MockFileSystem_Expecter) Stat(_a0 interface{}) *MockFileSystem_Stat_Call {
	return &MockFileSystem_Stat_Call{Call: _e.mock.On("Stat", _a0)}
}

func (_c *MockFileSystem_Stat_Call) Run(run func(_a0 string)) *MockFileSystem_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_Stat_Call) Return(_a0 fs.FileInfo, _a1 error) *MockFileSystem_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileSystem_Stat_Call) RunAndReturn(run func(string) (fs.FileInfo, error)) *MockFileSystem_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// SyncDir provides a mock function with given fields: _a0
func (_m *MockFileSystem) SyncDir(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SyncDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileSystem_SyncDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncDir'
type MockFileSystem_SyncDir_Call struct {
	*mock.Call
}

// SyncDir is a helper method to define mock.On call
//   - _a0 string
func (_e *MockFileSystem_Expecter) SyncDir(_a0 interface{}) *MockFileSystem_SyncDir_Call {
	return &MockFileSystem_SyncDir_Call{Call: _e.mock.On("SyncDir", _a0)}
}

func (_c *MockFileSystem_SyncDir_Call) Run(run func(_a0 string)) *MockFileSystem_SyncDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileSystem_SyncDir_Call) Return(_a0 error) *MockFileSystem_SyncDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileSystem_SyncDir_Call) RunAndReturn(run func(string) error) *MockFileSystem_SyncDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileSystem creates a new instance of MockFileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileSystem {
	mock := &MockFileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
