// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockFile is an autogenerated mock type for the File type
type MockFile struct {
	mock.Mock
}

type MockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFile) EXPECT() *MockFile_Expecter {
	return &MockFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockFile) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFile_Expecter) Close() *MockFile_Close_Call {
	return &MockFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFile_Close_Call) Run(run func()) *MockFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Close_Call) Return(_a0 error) *MockFile_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFile_Close_Call) RunAndReturn(run func() error) *MockFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockFile) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFile_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockFile_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockFile_Expecter) Name() *MockFile_Name_Call {
	return &MockFile_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockFile_Name_Call) Run(run func()) *MockFile_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Name_Call) Return(_a0 string) *MockFile_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFile_Name_Call) RunAndReturn(run func() string) *MockFile_Name_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function with given fields: _a0, _a1
func (_m *MockFile) ReadAt(_a0 []byte, _a1 int64) (int, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type MockFile_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - _a0 []byte
//   - _a1 int64
func (_e *MockFile_Expecter) ReadAt(_a0 interface{}, _a1 interface{}) *MockFile_ReadAt_Call {
	return &MockFile_ReadAt_Call{Call: _e.mock.On("ReadAt", _a0, _a1)}
}

func (_c *MockFile_ReadAt_Call) Run(run func(_a0 []byte, _a1 int64)) *MockFile_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(int64))
	})
	return _c
}

func (_c *MockFile_ReadAt_Call) Return(_a0 int, _a1 error) *MockFile_ReadAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_ReadAt_Call) RunAndReturn(run func([]byte, int64) (int, error)) *MockFile_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFull provides a mock function with given fields: _a0
func (_m *MockFile) ReadFull(_a0 []byte) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ReadFull")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_ReadFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFull'
type MockFile_ReadFull_Call struct {
	*mock.Call
}

// ReadFull is a helper method to define mock.On call
//   - _a0 []byte
func (_e *MockFile_Expecter) ReadFull(_a0 interface{}) *MockFile_ReadFull_Call {
	return &MockFile_ReadFull_Call{Call: _e.mock.On("ReadFull", _a0)}
}

func (_c *MockFile_ReadFull_Call) Run(run func(_a0 []byte)) *MockFile_ReadFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockFile_ReadFull_Call) Return(_a0 int, _a1 error) *MockFile_ReadFull_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_ReadFull_Call) RunAndReturn(run func([]byte) (int, error)) *MockFile_ReadFull_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function with given fields: _a0, _a1
func (_m *MockFile) Seek(_a0 int64, _a1 int) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type MockFile_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - _a0 int64
//   - _a1 int
func (_e *MockFile_Expecter) Seek(_a0 interface{}, _a1 interface{}) *MockFile_Seek_Call {
	return &MockFile_Seek_Call{Call: _e.mock.On("Seek", _a0, _a1)}
}

func (_c *MockFile_Seek_Call) Run(run func(_a0 int64, _a1 int)) *MockFile_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *MockFile_Seek_Call) Return(_a0 int64, _a1 error) *MockFile_Seek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_Seek_Call) RunAndReturn(run func(int64, int) (int64, error)) *MockFile_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with no fields
func (_m *MockFile) Sync() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFile_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockFile_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
func (_e *MockFile_Expecter) Sync() *MockFile_Sync_Call {
	return &MockFile_Sync_Call{Call: _e.mock.On("Sync")}
}

func (_c *MockFile_Sync_Call) Run(run func()) *MockFile_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Sync_Call) Return(_a0 error) *MockFile_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFile_Sync_Call) RunAndReturn(run func() error) *MockFile_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// Truncate provides a mock function with given fields: _a0
func (_m *MockFile) Truncate(_a0 int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Truncate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFile_Truncate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truncate'
type MockFile_Truncate_Call struct {
	*mock.Call
}

// Truncate is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockFile_Expecter) Truncate(_a0 interface{}) *MockFile_Truncate_Call {
	return &MockFile_Truncate_Call{Call: _e.mock.On("Truncate", _a0)}
}

func (_c *MockFile_Truncate_Call) Run(run func(_a0 int64)) *MockFile_Truncate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockFile_Truncate_Call) Return(_a0 error) *MockFile_Truncate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFile_Truncate_Call) RunAndReturn(run func(int64) error) *MockFile_Truncate_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *MockFile) Write(_a0 []byte) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 []byte
func (_e *MockFile_Expecter) Write(_a0 interface{}) *MockFile_Write_Call {
	return &MockFile_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *MockFile_Write_Call) Run(run func(_a0 []byte)) *MockFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockFile_Write_Call) Return(_a0 int, _a1 error) *MockFile_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockFile_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAt provides a mock function with given fields: _a0, _a1
func (_m *MockFile) WriteAt(_a0 []byte, _a1 int64) (int, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for WriteAt")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_WriteAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAt'
type MockFile_WriteAt_Call struct {
	*mock.Call
}

// WriteAt is a helper method to define mock.On call
//   - _a0 []byte
//   - _a1 int64
func (_e *MockFile_Expecter) WriteAt(_a0 interface{}, _a1 interface{}) *MockFile_WriteAt_Call {
	return &MockFile_WriteAt_Call{Call: _e.mock.On("WriteAt", _a0, _a1)}
}

func (_c *MockFile_WriteAt_Call) Run(run func(_a0 []byte, _a1 int64)) *MockFile_WriteAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(int64))
	})
	return _c
}

func (_c *MockFile_WriteAt_Call) Return(_a0 int, _a1 error) *MockFile_WriteAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_WriteAt_Call) RunAndReturn(run func([]byte, int64) (int, error)) *MockFile_WriteAt_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTo provides a mock function with given fields: _a0
func (_m *MockFile) WriteTo(_a0 [][]byte) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for WriteTo")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([][]byte) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([][]byte) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([][]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFile_WriteTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTo'
type MockFile_WriteTo_Call struct {
	*mock.Call
}

// WriteTo is a helper method to define mock.On call
//   - _a0 [][]byte
func (_e *MockFile_Expecter) WriteTo(_a0 interface{}) *MockFile_WriteTo_Call {
	return &MockFile_WriteTo_Call{Call: _e.mock.On("WriteTo", _a0)}
}

func (_c *MockFile_WriteTo_Call) Run(run func(_a0 [][]byte)) *MockFile_WriteTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([][]byte))
	})
	return _c
}

func (_c *MockFile_WriteTo_Call) Return(_a0 int, _a1 error) *MockFile_WriteTo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFile_WriteTo_Call) RunAndReturn(run func([][]byte) (int, error)) *MockFile_WriteTo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFile creates a new instance of MockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFile {
	mock := &MockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
